##### BEGIN image.wrapper/Dockerfile/image-header #####
FROM vcwebio/conteco.external.bash
##### END image.wrapper/Dockerfile/image-header #####

##### BEGIN image.wrapper/Dockerfile/conteco #####
ENTRYPOINT ["/conteco/bin/image/wrapper/entrypoint"]
##### END image.wrapper/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/git-repository/*
COPY ./ /conteco/git-repository/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
ENV CONTECO_ENTRYPOINT "bash"
WORKDIR /conteco/pwd
##### END image/Dockerfile/build-instructions #####

##### BEGIN image.wrapper/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="image" \
    CONTECO_NAME="wrapper" \
    CONTECO_TAG="v0.4.0" \
    CONTECO_BASE="external.bash" \
    CONTECO_BUILD="wrapper"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="image" \
      io.vcweb.name="wrapper" \
      io.vcweb.tag="v0.4.0" \
      io.vcweb.base="external.bash" \
      io.vcweb.build="wrapper" \
      io.vcweb.label="container Wrapper" \
      io.vcweb.description="The conteco.image.wrapper image holds the common functionality wrapper for all ContEco containers." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.image.wrapper --help" 
##### END image.wrapper/Dockerfile/env-labels-footer #####
