#!/usr/bin/env bash

export CONTECO_LABEL="kafka.base - ContEco"
export CONTECO_DESCRIPTION="Confluent Kafka Base image, with configuration changes."

export CONTECO_TYPE="kafka"
export CONTECO_NAME="base"
export CONTECO_TAG="5.4.0"

export CONTECO_BASE="external.kafka:5.4.0"
export CONTECO_BUILD="image-base"
