#!/usr/bin/env bash

export CONTECO_LABEL="container Wrapper"
export CONTECO_DESCRIPTION="The conteco.image.wrapper image holds the common functionality wrapper for all ContEco containers."

export CONTECO_TYPE="image"
export CONTECO_NAME="wrapper"
export CONTECO_TAG=""

export CONTECO_BASE="external.bash"
export CONTECO_BUILD="wrapper"
