#!/usr/bin/env bash

# changing from multiple methods to flag driven behaviour
# .container still needs rework to reflect this
# current functinality limited to simple build
# arguments need defining and extracting
(
    . executionplane-invoke "$0 $@"
	if [[ "$1" == "all" ]] ; then
		shift
	fi
    build $@
    executionplane-complete
)
